// Generated by CoffeeScript 1.4.0

/*

Game CoffeeScript class.

"One Class to rule them all,
One Class to find them,
One Class to bring them all
and in the darkness bind them."

@author: Marcin Wieprzkowicz (marcin.wieprzkowicz@gmail.com)
*/


(function() {
  var Game,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game = (function(_super) {

    __extends(Game, _super);

    Game.prototype.defaults = {
      game: {
        overlay: '#game .overlay',
        start: '#start-game'
      }
    };

    function Game(options, menu) {
      this.menu = menu;
      Game.__super__.constructor.apply(this, arguments);
      this.element = {
        game: {
          overlay: document.querySelector(this.options.game.overlay),
          start: document.querySelector(this.options.game.start)
        }
      };
      this.initAudio();
      this.map = new Map({}, this);
      this.character = new Character({
        id: 'character',
        klass: 'visualization'
      }, this.audio);
      this.map.add(this.character);
      this.control = new Control({}, this, this.map);
      this.control.addKeyboardEvents();
      if (Modernizr.touch) {
        this.control.showTouchItems().addControlEvents();
      }
    }

    Game.prototype.start = function() {
      var _this = this;
      this.fadeOut([this.element.game.overlay, this.menu.element.main.element], function() {
        return _this.setText(_this.element.game.start, 'Resume');
      });
      this.character.domElement.classList.remove('paused');
      this.globals.pause = false;
      this.animation = setInterval(function() {
        _this.map.handleCollisions();
        _this.map.draw();
      }, 50);
    };

    Game.prototype.pause = function() {
      clearInterval(this.animation);
      this.globals.pause = true;
      this.character.domElement.classList.add('paused');
    };

    Game.prototype.reset = function() {
      var _this = this;
      this.map.setDefaultPosition().closeDoors();
      this.character.reset();
      setTimeout(function() {
        return _this.setText(_this.element.game.start, 'Start game');
      }, 1000);
    };

    Game.prototype.theEnd = function() {
      var _this = this;
      this.pause();
      this.setText(this.menu.element.theEnd.header, 'The end');
      this.menu.element.theEnd.congratulations.style.display = 'block';
      this.fadeIn([this.element.game.overlay, this.menu.element.section.credits], function() {
        return _this.reset();
      });
      this.flexcrollContent(this.menu.element.section.credits);
    };

    Game.prototype.gameOver = function(speed) {
      var _this = this;
      this.character.domElement.classList.add('death');
      this.character.domElement.style[this.globals.css.transform] = "translate3d(0, " + (Math.abs(speed) * 20) + "px, 0)";
      setTimeout(function() {
        _this.pause();
        return _this.fadeIn([_this.element.game.overlay, _this.menu.element.section.gameOver], function() {
          return _this.reset();
        });
      }, 1000);
    };

    Game.prototype.aboutMe = function() {
      var _this = this;
      this.pause();
      this.fadeIn([this.element.game.overlay, this.menu.element.section.aboutMe], function() {
        return _this.reset();
      });
      this.flexcrollContent(this.menu.element.section.aboutMe);
    };

    Game.prototype.initAudio = function() {
      if (Modernizr.ismobile) {
        buzz.defaults.preload = 'none';
      }
      buzz.defaults.formats = ['ogg', 'm4a'];
      buzz.defaults.volume = Modernizr.ismobile ? 0 : 15;
      this.audio = {
        background: new buzz.sound('audio/background', {
          autoplay: !Modernizr.ismobile,
          loop: true,
          volume: 10
        }),
        running: new buzz.sound('audio/running', {
          loop: true
        }),
        landing: new buzz.sound('audio/landing', {
          loop: false
        }),
        openingDoors: new buzz.sound('audio/opening-doors', {
          loop: false
        })
      };
      this.sounds = new buzz.group([this.audio.running, this.audio.landing, this.audio.openingDoors]);
    };

    return Game;

  })(Base);

  (typeof exports !== "undefined" && exports !== null ? exports : this).Game = Game;

}).call(this);
