// Generated by CoffeeScript 1.4.0
(function() {
  var Platform;

  Platform = (function() {

    Platform.prototype.defaults = {
      offset: 0,
      range: 489,
      direction: 'normal'
    };

    function Platform(platform) {
      var offset, range;
      offset = platform.getAttribute('data-offset');
      range = platform.getAttribute('data-range');
      this.element = platform;
      this.child = platform.firstElementChild;
      this.direction = this.defaults.direction;
      this.offset = offset != null ? parseInt(offset, 10) : this.defaults.offset;
      this.range = range != null ? parseInt(range, 10) : this.defaults.range;
      this.width = platform.clientWidth;
      this.child.position.x += this.offset;
    }

    return Platform;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Platform = Platform;

}).call(this);
