// Generated by CoffeeScript 1.4.0

/*

Platform CoffeeScript class.

@author: Marcin Wieprzkowicz (marcin.wieprzkowicz@gmail.com)
*/


(function() {
  var Platform;

  Platform = (function() {

    Platform.prototype.defaults = {
      offset: 0,
      range: 489,
      direction: 'normal'
    };

    function Platform(element) {
      var offset, range, solidIndex;
      offset = element.getAttribute('data-offset');
      range = element.getAttribute('data-range');
      this.element = element;
      this.direction = this.defaults.direction;
      this.offset = offset != null ? parseInt(offset, 10) : this.defaults.offset;
      this.range = range != null ? parseInt(range, 10) : this.defaults.range;
      this.width = element.clientWidth;
      solidIndex = parseInt(element.firstElementChild.getAttribute('data-index'), 10);
      this.solid = window.deadHollow.solids[solidIndex];
      this.solid.position.x += this.offset;
    }

    return Platform;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Platform = Platform;

}).call(this);
