// Generated by CoffeeScript 1.4.0

/*

Solid CoffeeScript class.

@author: Marcin Wieprzkowicz (marcin.wieprzkowicz@gmail.com)
*/


(function() {
  var Solid;

  Solid = (function() {

    function Solid(element) {
      this.element = element;
      this.position = this.getPosition(element);
      if (element.classList.contains('platform')) {
        this.height = 1;
        if (element.classList.contains('moving')) {
          this.width = 94;
          this.position.x += 27;
          this.position.y += 10;
        } else if (element.classList.contains('cropped')) {
          this.width = 88;
        } else if (element.classList.contains('floorDirection')) {
          this.width = 161;
          this.position.x += 60;
          this.position.y += 24;
        } else if (element.classList.contains('floorAltDirection')) {
          this.width = 60;
          this.position.y += 24;
        } else {
          this.width = 85;
          this.position.x += 27;
        }
      } else if (element.classList.contains('box')) {
        this.height = 95;
        this.width = 147;
        this.position.y += 8;
        this.position.x += 21;
      } else {
        this.height = element.clientHeight;
        this.width = element.clientWidth;
      }
    }

    Solid.prototype.getPosition = function(element) {
      var x, y;
      x = 0;
      y = 0;
      while (element.offsetParent) {
        x += element.offsetLeft;
        y += element.offsetTop;
        if (element.offsetParent.id === 'map') {
          break;
        }
        element = element.offsetParent;
      }
      return {
        x: x,
        y: y
      };
    };

    Solid.prototype.getHeightAgain = function() {
      return this.height = this.element.clientHeight;
    };

    return Solid;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Solid = Solid;

}).call(this);
